icons:
  - name: 1024-14_Bus_frei.svg
    size: [54, 42]
  - name: 1024-16_StadtBahn_frei.svg
    size: [54, 42]
  - name: 1026-32_Linienverkehr_frei.svg
    size: [54, 42]
  - name: 1048-16_Bus.svg
    size: [75, 42]
  - name: 1048-19_StadtBahn.svg
    size: [75, 42]
  - name: 123_Baustelle.svg
    size: [42, 37]
  - name: 131_Ampel.svg
    size: [42, 42]
  - name: 206_Stop.svg
    size: [42, 42]
  - name: 208_Gegenverkehr_hat_Vorrang.svg
    size: [42, 42]
  - name: 209-10_Fahrtrichtung_links.svg
    size: [42, 42]
  - name: 209-20_Fahrtrichtung_rechts.svg
    size: [42, 42]
  - name: 209-30_Fahrtrichtung_gradeaus.svg
    size: [42, 42]
  - name: 209-31_Fahrtrichtung_links_und_rechts.svg
    size: [42, 42]
  - name: 211-10_Links.svg
    size: [42, 42]
  - name: 211-20_Rechts.svg
    size: [42, 42]
  - name: 214-10_geradeaus_links.svg
    size: [42, 42]
  - name: 214-20_geradeaus_rechts.svg
    size: [42, 42]
  - name: 215_Kreisverkehr.svg
    size: [42, 42]
  - name: 220-10_Einbahnstrasse_links.svg
    size: [76, 29]
  - name: 220-20_Einbahnstrasse_rechts.svg
    size: [76, 29]
  - name: 222-10_links_vorbei.svg
    size: [42, 42]
  - name: 222-20_rechts_vorbei.svg
    size: [42, 42]
  - name: 224-51_Schulbus-Haltestelle.svg
    size: [42, 42]
  - name: 250_Verbot_der_Durchfahrt.svg
    size: [42, 42]
  - name: 267_Spardose.svg
    size: [42, 42]
  - name: 274-1-50_Zone_30.svg
    size: [42, 42]
  - name: 274-1-51_Zone_20.svg
    size: [42, 42]
  - name: 274-2-50_Zone_30_Ende.svg
    size: [42, 42]
  - name: 274-2-51_Zone_20_Ende.svg
    size: [42, 42]
  - name: 283-10_Halteverbot_Pfeil_nach_oben.svg
    size: [42, 42]
  - name: 283-20_Halteverbot_Pfeil_nach_unten.svg
    size: [42, 42]
  - name: 283-30_Halteverbot_beide_Pfeile.svg
    size: [42, 42]
  - name: 283-50_Halteverbot.svg
    size: [42, 42]
  - name: 286-10.svg
    size: [42, 42]
  - name: 286-20.svg
    size: [42, 42]
  - name: 286-30.svg
    size: [42, 42]
  - name: 286-50.svg
    size: [42, 42]
  - name: 301.svg
    size: [41, 37]
  - name: 306.svg
    size: [42, 42]
  - name: 307.svg
    size: [42, 42]
  - name: 308_Vorrang_vor_dem_Gegenverkehr.svg
    size: [42, 42]
  - name: 357_Sackgasse.svg
    size: [42, 42]
  - name: 454-10_Umleitung_links.svg
    size: [76, 29]
  - name: 454-20_Umleitung_rechts.svg
    size: [76, 29]
  - name: 455-10_U3_links.svg
    size: [29, 42]
  - name: 455-11_U3_links_gerade.svg
    size: [29, 42]
  - name: 455-12_U3_schraeg_links.svg
    size: [29, 42]
  - name: 455-20_U3_rechts.svg
    size: [29, 42]
  - name: 455-21_U3_rechts_gerade.svg
    size: [29, 42]
  - name: 455-22_U3_schraeg_rechts.svg
    size: [29, 42]
  - name: 455-30_U3_geradeaus.svg
    size: [29, 42]
  - name: 457_Umleitung.svg
    size: [76, 29]
  - name: 459_Umleitung_Ende.svg
    size: [76, 29]
  - name: 600-30_Sperrschranke.svg
    size: [76, 29]
  - name: 600-31_Sperrschranke_nicht_noetig.svg
    size: [76, 29]
  - name: 600-32_Sperrschranke_nicht_noetig.svg
    size: [76, 29]
  - name: 600-33_Sperrschranke_breit_nicht_noetig.svg
    size: [76, 29]
  - name: 605-10_Leitbarke_links.svg
    size: [20, 75]
  - name: 605-20_Leitbarke_rechts.svg
    size: [20, 75]
  - name: 610-40_Pylon_klein.svg
    size: [55, 76]
  - name: Bus.svg
    size: [42, 42]
  - name: Haltestelle_durchgestrichen.svg
    size: [42, 42]
  - name: Haltestelle.svg
    size: [42, 42]
  - name: keine_Barrierefreiheit.svg
    size: [42, 42]
  - name: Strassensperre.svg
    size: [76, 29]
  - name: Vorfahrt_achten.svg
    size: [42, 42]
  - name: X-Symbol.svg
    size: [42, 42]
