version: 1

formatters:
  simple:
    format: '%(asctime)s - %(name)s - %(levelname)s - %(message)s'
  stats:
    format: '%(asctime)s|%(name)s|%(message)s'

handlers:
  console:
    class: logging.StreamHandler
    level: DEBUG
    formatter: simple
    stream: ext://sys.stdout

  stats:
    class: logging.StreamHandler
    level: DEBUG
    formatter: stats
    stream: ext://sys.stdout

loggers:
  munimap:
    level: DEBUG
    handlers: [console]
    propagate: no

  munimap.proxy:
    level: DEBUG
    handlers: [console]
    propagate: no

  munimap.alkis:
    level: DEBUG
    handlers: [console]
    propagate: no

  munimap.transfer:
    level: DEBUG
    handlers: [console]
    propagate: no

  munimap.token:
    level: DEBUG
    handlers: [console]
    propagate: no
  
  munimap.layers:
    level: DEBUG
    handlers: [console]
    propagate: no
  
  munimap.digitize:
    level: DEBUG
    handlers: [console]
    propagate: no
  
  munimap.print:
    level: DEBUG
    handlers: [console]
    propagate: no
  
  munimap.stats:
    level: INFO
    handlers: [stats]
    propagate: no

root:
  level: DEBUG
  handlers: [console]
