from setuptools import setup, find_packages

setup(
    name='munimap',
    version="1.0",
    url='<enter URL here>',
    license='BSD',
    maintainer='terrestris GmbH & Co. KG',
    maintainer_email='info@terrestris.de',
    description='Municipality map with street index, search grid, etc.',
    packages=find_packages(),
    include_package_data=True,
    zip_safe=False,
    platforms='any',
    install_requires=[
        'Flask==0.10.1',
        'Flask-Script==2.0.5',
        'Flask-Login==0.3.2',
        'Flask-SQLAlchemy==2.1',
        'Flask-Assets==0.11',
        'Flask-Mail==0.9.1',
        'Flask-WTF==0.12',
        'SQLAlchemy==1.0.8',
        'bcrypt==3.1.7',
        'dictspec==0.2.1',
        'requests==2.8.1',
        'psycopg2==2.8.3',
        'Jinja2==2.8',
        'MarkupSafe==0.23',
        'PyYAML==3.11',
        'Werkzeug==0.10.4',
        'Rtree==0.8.2',
        'PyHyphen==3.0.1',
        'reportlab==3.2.0',
        'itsdangerous==0.24',
        'libsass==0.8.3',
        'Flask-Babel==0.9',
        'Shapely==1.5.12'
    ],
)
