x-munimap-db-image: &munimap-db-image postgis/postgis:18-3.6-alpine

services:
  munimap-nginx:
    image: nginx:1.27.1-alpine
    ports:
      - "80:80"
      - "4000:4000"
    volumes:
      - ./munimap-nginx/favicon.ico:/opt/etc/munimap/favicon.ico
      - ./munimap-nginx/default.conf:/etc/nginx/conf.d/default.conf
    extra_hosts:
      - host.docker.internal:host-gateway
    depends_on:
      - munimap-app
    profiles:
      - prod

  munimap-nginx-dev:
    image: nginx:1.27.1-alpine
    ports:
      - "80:80"
      - "4000:4000"
    volumes:
      - ./munimap-nginx/favicon.ico:/opt/etc/munimap/favicon.ico
      - ./munimap-nginx/default-dev.conf:/etc/nginx/conf.d/default.conf
    extra_hosts:
      - host.docker.internal:host-gateway
    profiles:
      - dev

  munimap-app:
    container_name: munimap-app
    build:
      context: ../
      args:
        ANOL_COMMIT_HASH: master
    volumes:
      - ../dev/configs:/opt/etc/munimap/configs
      - ./munimap-app/alembic.ini:/opt/etc/munimap/configs/alembic.ini
      - ./munimap-app/munimap.conf:/opt/etc/munimap/configs/munimap.conf
      - ../dev/data:/opt/etc/munimap/data
      - ../dev/printqueue:/opt/etc/munimap/printqueue
    depends_on:
      munimap-postgis:
        condition: service_healthy
    profiles:
      - prod

  munimap-print-worker:
    build:
      context: ../
      args:
        ANOL_COMMIT_HASH: master
    command: ['python3', '-m', 'munimap.queue.worker', '--config-file=/opt/etc/munimap/configs/munimap.conf']
    volumes:
      - ../dev/configs:/opt/etc/munimap/configs
      - ./munimap-app/alembic.ini:/opt/etc/munimap/configs/alembic.ini
      - ./munimap-app/munimap.conf:/opt/etc/munimap/configs/munimap.conf
      - ../dev/printqueue:/opt/etc/munimap/printqueue
    environment:
      # Because of failing DIN A0 prints in production, the heap size needed to be increased to 4gb
      # TODO: When removing the mapfish CLI this option can be removed from this container
      JAVA_OPTS: -Xmx4096m -Djava.awt.headless=true
      RUN_ALEMBIC: false
    depends_on:
      munimap-postgis:
        condition: service_healthy
    profiles:
      - prod

  munimap-postgis:
    image: *munimap-db-image
    ports:
      - "5555:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    volumes:
      - ./munimap-postgis/postgresql_init_data:/docker-entrypoint-initdb.d
      - ./munimap-postgis/postgresql_data:/var/lib/postgresql/:Z
    profiles:
      - dev
      - prod
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U postgres -d postgres"]
      interval: 10s
      timeout: 3s
      retries: 10

  munimap-print:
    restart: unless-stopped
    image: camptocamp/mapfish_print:3.30.11
    ports:
      - "8888:8080"
    environment:
      # Because of failing DIN A0 prints in production, the heap size needed to be increased to 4gb
      JAVA_OPTS: -Xmx4096m -Djava.awt.headless=true
    volumes:
      - ../dev/configs/mapfish:/usr/local/tomcat/webapps/ROOT/print-apps/munimap
